In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
### Define the vocabulary size

voc_size = 10000

In [14]:
## One hot representation for every word
one_hot_repe = [one_hot(words, voc_size) for words in sent]
one_hot_repe    

[[3217, 4820, 9503, 2596],
 [3217, 4820, 9503, 600],
 [3217, 2169, 9503, 7625],
 [4479, 2028, 9046, 9433, 1206],
 [4479, 2028, 9046, 9433, 8710],
 [7251, 3217, 1454, 9503, 8805],
 [6731, 9640, 7646, 9433]]

In [15]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [18]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repe,padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3217, 4820, 9503, 2596],
       [   0,    0,    0,    0, 3217, 4820, 9503,  600],
       [   0,    0,    0,    0, 3217, 2169, 9503, 7625],
       [   0,    0,    0, 4479, 2028, 9046, 9433, 1206],
       [   0,    0,    0, 4479, 2028, 9046, 9433, 8710],
       [   0,    0,    0, 7251, 3217, 1454, 9503, 8805],
       [   0,    0,    0,    0, 6731, 9640, 7646, 9433]], dtype=int32)

In [19]:
### Feature representation
dim = 10


In [20]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')


2024-10-26 07:09:50.357465: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2024-10-26 07:09:50.357590: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:129] retrieving CUDA diagnostic information for host: panda-dellg155510
2024-10-26 07:09:50.357602: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:136] hostname: panda-dellg155510
2024-10-26 07:09:50.357849: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:159] libcuda reported version is: 535.183.1
2024-10-26 07:09:50.357876: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] kernel reported version is: 535.183.1
2024-10-26 07:09:50.357882: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:241] kernel version seems to match DSO: 535.183.1


In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[-0.03569342,  0.02827174,  0.03948599,  0.00390595,  0.04665916,
        -0.02902162, -0.0145851 , -0.02760065,  0.02817198,  0.02619573],
       [-0.03569342,  0.02827174,  0.03948599,  0.00390595,  0.04665916,
        -0.02902162, -0.0145851 , -0.02760065,  0.02817198,  0.02619573],
       [-0.03569342,  0.02827174,  0.03948599,  0.00390595,  0.04665916,
        -0.02902162, -0.0145851 , -0.02760065,  0.02817198,  0.02619573],
       [-0.03569342,  0.02827174,  0.03948599,  0.00390595,  0.04665916,
        -0.02902162, -0.0145851 , -0.02760065,  0.02817198,  0.02619573],
       [-0.01856464, -0.00771762, -0.01545639, -0.04779635, -0.0357913 ,
         0.01890928,  0.02382772, -0.03282739, -0.00104898,  0.03512641],
       [ 0.04371433,  0.01198652,  0.02874452,  0.00924703,  0.03449604,
        -0.04223558, -0.0075116 ,  0.00405531, -0.02543694, -0.03489591],
       [ 0.01149774, -0.01934819,  0.01227925, -0.04635138,  0.01423974,
        -0.04072596,  0.01253569,  0.02531869

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 3217, 4820, 9503, 2596], dtype=int32)